theme: jekyll-theme-minimal
title: ADA Arabs Data Scientist Website
description: Project website of the Arabs Data Scientists Group
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
